version: "3.10"
services:
  app:
    build: .
    command: python main.py
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${database}
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}

